In [1]:
import pandas as pd
import numpy as np

### Question 1: What's the version of Pandas that you installed?

In [2]:
print('The version of pandas installed is ', pd.__version__)

The version of pandas installed is  2.3.1


#### Getting the data

In [3]:
data= pd.read_csv('car_fuel_efficiency.csv')
data.head()

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
0                  170            3.0       159.0     3413.433759   
1                  130            5.0        97.0     3149.664934   
2                  170            NaN        78.0     3079.038997   
3                  220            4.0         NaN     2542.392402   
4                  210            1.0       140.0     3460.870990   

   acceleration  model_year  origin fuel_type         drivetrain  num_doors  \
0          17.7        2003  Europe  Gasoline    All-wheel drive        0.0   
1          17.8        2007     USA  Gasoline  Front-wheel drive        0.0   
2          15.1        2018  Europe  Gasoline  Front-wheel drive        0.0   
3          20.2        2009     USA    Diesel    All-wheel drive        2.0   
4          14.4        2009  Europe  Gasoline    All-wheel drive        2.0   

   fuel_efficiency_mpg  
0            13.231729  
1            13.688217  
2            14.246341  
3            16.912736  
4            12.488369

### Question 2: How many records are in the dataset?

In [4]:
print('The records in dataset are: ',data.shape[0])

The records in dataset are:  9704


### Question 3: How many fuel types are presented in the dataset?

In [5]:
print('The number of fuel types in the dataset are: ', data.fuel_type.nunique())

The number of fuel types in the dataset are:  2


### Question 4: How many columns in the dataset have missing values?

In [6]:
print('The number of columns in the dataset having missing values are:\n',data.isna().sum())

The number of columns in the dataset having missing values are:
 engine_displacement      0
num_cylinders          482
horsepower             708
vehicle_weight           0
acceleration           930
model_year               0
origin                   0
fuel_type                0
drivetrain               0
num_doors              502
fuel_efficiency_mpg      0
dtype: int64


### Question 5: What's the maximum fuel efficiency of cars from Asia?

In [7]:
print('The maximum fuel efficiency of cars from Asia is ', data.groupby('origin').fuel_efficiency_mpg.max())

The maximum fuel efficiency of cars from Asia is  origin
Asia      23.759123
Europe    25.967222
USA       24.971452
Name: fuel_efficiency_mpg, dtype: float64


### Question 6:

#### Median value of horsepower

Question 6.1. Find the median value of horsepower column in the dataset

In [8]:
data.horsepower.median()

np.float64(149.0)

Question 6.2. Next, calculate the most frequent value of the same horsepower column

In [9]:
data.horsepower.mode()[0]

np.float64(152.0)

Question 6.3. Use fillna method to fill the missing values in horsepower column with the most frequent value from the previous step

In [10]:
data.fillna({'horsepower':data.horsepower.mode()[0]}, inplace= True)

In [11]:
data.horsepower.isna().sum()

np.int64(0)

Question 6.4. Now, calculate the median value of horsepower once again.

In [12]:
data.horsepower.median()

np.float64(152.0)

### Yes, It has increased.

### Question 7

#### Sum of weights

Question 7.1. Select all the cars from Asia

In [13]:
data[data['origin'] == 'Asia']

engine_displacement  num_cylinders  horsepower  vehicle_weight  \
8                     250            1.0       174.0     2714.219310   
12                    320            5.0       145.0     2783.868974   
14                    200            6.0       160.0     3582.687368   
20                    150            3.0       197.0     2231.808142   
21                    160            4.0       133.0     2659.431451   
...                   ...            ...         ...             ...   
9688                  260            4.0       152.0     3948.404625   
9692                  180            3.0       188.0     3680.341381   
9693                  280            2.0       148.0     2545.070139   
9698                  180            1.0       131.0     3107.427820   
9703                  270            3.0       140.0     2908.043477   

      acceleration  model_year origin fuel_type         drivetrain  num_doors  \
8             10.3        2016   Asia    Diesel  Front-wheel drive       -1.0   
12            15.1        2010   Asia    Diesel    All-wheel drive        1.0   
14            14.9        2007   Asia    Diesel    All-wheel drive        0.0   
20            18.7        2011   Asia  Gasoline  Front-wheel drive        1.0   
21             NaN        2016   Asia  Gasoline  Front-wheel drive       -1.0   
...            ...         ...    ...       ...                ...        ...   
9688          15.5        2018   Asia    Diesel    All-wheel drive       -1.0   
9692          18.0        2016   Asia  Gasoline  Front-wheel drive        1.0   
9693          15.6        2012   Asia    Diesel    All-wheel drive        0.0   
9698          13.2        2005   Asia  Gasoline  Front-wheel drive       -2.0   
9703          14.7        2005   Asia    Diesel    All-wheel drive       -1.0   

      fuel_efficiency_mpg  
8               16.823554  
12              16.175820  
14              11.871091  
20              18.889083  
21              16.077730  
...                   ...  
9688            11.054830  
9692            11.711653  
9693            17.202782  
9698            13.933716  
9703            14.884467  

[3247 rows x 11 columns]

Question 7.2. Select only columns vehicle_weight and model_year

In [14]:
data[data['origin'] == 'Asia'][['vehicle_weight', 'model_year']]

vehicle_weight  model_year
8        2714.219310        2016
12       2783.868974        2010
14       3582.687368        2007
20       2231.808142        2011
21       2659.431451        2016
...              ...         ...
9688     3948.404625        2018
9692     3680.341381        2016
9693     2545.070139        2012
9698     3107.427820        2005
9703     2908.043477        2005

[3247 rows x 2 columns]

Question 7.3. Select the first 7 values

In [15]:
data[data['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(n= 7)

vehicle_weight  model_year
8      2714.219310        2016
12     2783.868974        2010
14     3582.687368        2007
20     2231.808142        2011
21     2659.431451        2016
34     2844.227534        2014
38     3761.994038        2019

Question 7.4. Get the underlying NumPy array. Let's call it X

In [16]:
X= data[data['origin'] == 'Asia'][['vehicle_weight', 'model_year']].head(n= 7).values
X

array([[2714.21930965, 2016.        ],
       [2783.86897424, 2010.        ],
       [3582.68736772, 2007.        ],
       [2231.8081416 , 2011.        ],
       [2659.43145076, 2016.        ],
       [2844.22753389, 2014.        ],
       [3761.99403819, 2019.        ]])

Question 7.5. Compute matrix-matrix multiplication between the transpose of X and X. To get the transpose, use X.T. Let's call the result XTX.

In [17]:
XTX= X.T.dot(X)
XTX

array([[62248334.33150762, 41431216.5073268 ],
       [41431216.5073268 , 28373339.        ]])

Question 7.6. Invert XTX

In [18]:
XTX_inv= np.linalg.inv(XTX)
XTX_inv

array([[ 5.71497081e-07, -8.34509443e-07],
       [-8.34509443e-07,  1.25380877e-06]])

Question 7.7. Create an array y with values [1100, 1300, 800, 900, 1000, 1100, 1200]

In [19]:
y= np.array([1100, 1300, 800, 900, 1000, 1100, 1200])
y

array([1100, 1300,  800,  900, 1000, 1100, 1200])

Question 7.8. Multiply the inverse of XTX with the transpose of X, and then multiply the result by y. Call the result w.

In [20]:
w= XTX_inv.dot(X.T).dot(y)
w

array([0.01386421, 0.5049067 ])

Question 7.9.What's the sum of all the elements of the result?

In [21]:
w.sum()

np.float64(0.5187709081074016)

### 0.51